services:
  - type: web
    name: mca-analyzer-backend
    env: python
    rootDir: backend
    plan: free
    region: singapore
  
    buildCommand: "apt-get update && apt-get install -y gfortran libblas-dev liblapack-dev && pip install -r requirements.txt"
    
    startCommand: "gunicorn run:app"
    
    envVars:
      - key: DEV_MODE
        value: False